package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ClaseTipo generated by hbm2java
 */
public class ClaseTipo  implements java.io.Serializable {


     private Integer claseTipoId;
     private Tipo tipo;
     private String claseTipoDescripcion;
     private String claseTipoRef;
     private Double claseTipoCostoEgreso;
     private Double claseTipoCostoIngreso;
     private Integer claseTipoPuntos;
     private Date claseTipoFechaCreacion;
     private Date claseTipoFechaModificacion;
     private Set<Egreso> egresos = new HashSet<Egreso>(0);
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<Puntos> puntoses = new HashSet<Puntos>(0);
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public ClaseTipo() {
    }

	
    public ClaseTipo(Integer claseTipoId) {
        this.claseTipoId = claseTipoId;
    }
    public ClaseTipo(Integer claseTipoId, Tipo tipo, String claseTipoDescripcion, String claseTipoRef, Double claseTipoCostoEgreso, Double claseTipoCostoIngreso, Integer claseTipoPuntos, Date claseTipoFechaCreacion, Date claseTipoFechaModificacion, Set<Egreso> egresos, Set<Producto> productos, Set<Puntos> puntoses, Set<Servicio> servicios) {
       this.claseTipoId = claseTipoId;
       this.tipo = tipo;
       this.claseTipoDescripcion = claseTipoDescripcion;
       this.claseTipoRef = claseTipoRef;
       this.claseTipoCostoEgreso = claseTipoCostoEgreso;
       this.claseTipoCostoIngreso = claseTipoCostoIngreso;
       this.claseTipoPuntos = claseTipoPuntos;
       this.claseTipoFechaCreacion = claseTipoFechaCreacion;
       this.claseTipoFechaModificacion = claseTipoFechaModificacion;
       this.egresos = egresos;
       this.productos = productos;
       this.puntoses = puntoses;
       this.servicios = servicios;
    }
   
    public Integer getClaseTipoId() {
        return this.claseTipoId;
    }
    
    public void setClaseTipoId(Integer claseTipoId) {
        this.claseTipoId = claseTipoId;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getClaseTipoDescripcion() {
        return this.claseTipoDescripcion;
    }
    
    public void setClaseTipoDescripcion(String claseTipoDescripcion) {
        this.claseTipoDescripcion = claseTipoDescripcion;
    }
    public String getClaseTipoRef() {
        return this.claseTipoRef;
    }
    
    public void setClaseTipoRef(String claseTipoRef) {
        this.claseTipoRef = claseTipoRef;
    }
    public Double getClaseTipoCostoEgreso() {
        return this.claseTipoCostoEgreso;
    }
    
    public void setClaseTipoCostoEgreso(Double claseTipoCostoEgreso) {
        this.claseTipoCostoEgreso = claseTipoCostoEgreso;
    }
    public Double getClaseTipoCostoIngreso() {
        return this.claseTipoCostoIngreso;
    }
    
    public void setClaseTipoCostoIngreso(Double claseTipoCostoIngreso) {
        this.claseTipoCostoIngreso = claseTipoCostoIngreso;
    }
    public Integer getClaseTipoPuntos() {
        return this.claseTipoPuntos;
    }
    
    public void setClaseTipoPuntos(Integer claseTipoPuntos) {
        this.claseTipoPuntos = claseTipoPuntos;
    }
    public Date getClaseTipoFechaCreacion() {
        return this.claseTipoFechaCreacion;
    }
    
    public void setClaseTipoFechaCreacion(Date claseTipoFechaCreacion) {
        this.claseTipoFechaCreacion = claseTipoFechaCreacion;
    }
    public Date getClaseTipoFechaModificacion() {
        return this.claseTipoFechaModificacion;
    }
    
    public void setClaseTipoFechaModificacion(Date claseTipoFechaModificacion) {
        this.claseTipoFechaModificacion = claseTipoFechaModificacion;
    }
    public Set<Egreso> getEgresos() {
        return this.egresos;
    }
    
    public void setEgresos(Set<Egreso> egresos) {
        this.egresos = egresos;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
    public Set<Puntos> getPuntoses() {
        return this.puntoses;
    }
    
    public void setPuntoses(Set<Puntos> puntoses) {
        this.puntoses = puntoses;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


