package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer clienteId;
     private String clienteNombre;
     private String clienteApellido;
     private String clienteNumeroIdentificacion;
     private String clienteNumeroCelular;
     private String clienteNumeroTelefono;
     private String clienteDireccion;
     private String clienteBarrio;
     private String clienteCorreoElctronico;
     private Date clienteFechaNacimiento;
     private Date clienteFechaCreacion;
     private Date clienteFechaModificacion;
     private Set<Entrada> entradas = new HashSet<Entrada>(0);
     private Set<Salida> salidas = new HashSet<Salida>(0);

    public Cliente() {
    }

	
    public Cliente(Integer clienteId, String clienteNombre, String clienteApellido, String clienteNumeroIdentificacion, String clienteNumeroCelular, String clienteDireccion, String clienteBarrio) {
        this.clienteId = clienteId;
        this.clienteNombre = clienteNombre;
        this.clienteApellido = clienteApellido;
        this.clienteNumeroIdentificacion = clienteNumeroIdentificacion;
        this.clienteNumeroCelular = clienteNumeroCelular;
        this.clienteDireccion = clienteDireccion;
        this.clienteBarrio = clienteBarrio;
    }
    public Cliente(Integer clienteId, String clienteNombre, String clienteApellido, String clienteNumeroIdentificacion, String clienteNumeroCelular, String clienteNumeroTelefono, String clienteDireccion, String clienteBarrio, String clienteCorreoElctronico, Date clienteFechaNacimiento, Date clienteFechaCreacion, Date clienteFechaModificacion, Set<Entrada> entradas, Set<Salida> salidas) {
       this.clienteId = clienteId;
       this.clienteNombre = clienteNombre;
       this.clienteApellido = clienteApellido;
       this.clienteNumeroIdentificacion = clienteNumeroIdentificacion;
       this.clienteNumeroCelular = clienteNumeroCelular;
       this.clienteNumeroTelefono = clienteNumeroTelefono;
       this.clienteDireccion = clienteDireccion;
       this.clienteBarrio = clienteBarrio;
       this.clienteCorreoElctronico = clienteCorreoElctronico;
       this.clienteFechaNacimiento = clienteFechaNacimiento;
       this.clienteFechaCreacion = clienteFechaCreacion;
       this.clienteFechaModificacion = clienteFechaModificacion;
       this.entradas = entradas;
       this.salidas = salidas;
    }
   
    public Integer getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(Integer clienteId) {
        this.clienteId = clienteId;
    }
    public String getClienteNombre() {
        return this.clienteNombre;
    }
    
    public void setClienteNombre(String clienteNombre) {
        this.clienteNombre = clienteNombre;
    }
    public String getClienteApellido() {
        return this.clienteApellido;
    }
    
    public void setClienteApellido(String clienteApellido) {
        this.clienteApellido = clienteApellido;
    }
    public String getClienteNumeroIdentificacion() {
        return this.clienteNumeroIdentificacion;
    }
    
    public void setClienteNumeroIdentificacion(String clienteNumeroIdentificacion) {
        this.clienteNumeroIdentificacion = clienteNumeroIdentificacion;
    }
    public String getClienteNumeroCelular() {
        return this.clienteNumeroCelular;
    }
    
    public void setClienteNumeroCelular(String clienteNumeroCelular) {
        this.clienteNumeroCelular = clienteNumeroCelular;
    }
    public String getClienteNumeroTelefono() {
        return this.clienteNumeroTelefono;
    }
    
    public void setClienteNumeroTelefono(String clienteNumeroTelefono) {
        this.clienteNumeroTelefono = clienteNumeroTelefono;
    }
    public String getClienteDireccion() {
        return this.clienteDireccion;
    }
    
    public void setClienteDireccion(String clienteDireccion) {
        this.clienteDireccion = clienteDireccion;
    }
    public String getClienteBarrio() {
        return this.clienteBarrio;
    }
    
    public void setClienteBarrio(String clienteBarrio) {
        this.clienteBarrio = clienteBarrio;
    }
    public String getClienteCorreoElctronico() {
        return this.clienteCorreoElctronico;
    }
    
    public void setClienteCorreoElctronico(String clienteCorreoElctronico) {
        this.clienteCorreoElctronico = clienteCorreoElctronico;
    }
    public Date getClienteFechaNacimiento() {
        return this.clienteFechaNacimiento;
    }
    
    public void setClienteFechaNacimiento(Date clienteFechaNacimiento) {
        this.clienteFechaNacimiento = clienteFechaNacimiento;
    }
    public Date getClienteFechaCreacion() {
        return this.clienteFechaCreacion;
    }
    
    public void setClienteFechaCreacion(Date clienteFechaCreacion) {
        this.clienteFechaCreacion = clienteFechaCreacion;
    }
    public Date getClienteFechaModificacion() {
        return this.clienteFechaModificacion;
    }
    
    public void setClienteFechaModificacion(Date clienteFechaModificacion) {
        this.clienteFechaModificacion = clienteFechaModificacion;
    }
    public Set<Entrada> getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set<Entrada> entradas) {
        this.entradas = entradas;
    }
    public Set<Salida> getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set<Salida> salidas) {
        this.salidas = salidas;
    }




}


