package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * ColaboradorServicio generated by hbm2java
 */
public class ColaboradorServicio  implements java.io.Serializable {


     private ColaboradorServicioId id;
     private Colaborador colaborador;
     private Servicio servicio;
     private Date colaboradorServicioFechaIni;
     private Date colaboradorServicioFechaFin;

    public ColaboradorServicio() {
    }

	
    public ColaboradorServicio(ColaboradorServicioId id, Colaborador colaborador, Servicio servicio) {
        this.id = id;
        this.colaborador = colaborador;
        this.servicio = servicio;
    }
    public ColaboradorServicio(ColaboradorServicioId id, Colaborador colaborador, Servicio servicio, Date colaboradorServicioFechaIni, Date colaboradorServicioFechaFin) {
       this.id = id;
       this.colaborador = colaborador;
       this.servicio = servicio;
       this.colaboradorServicioFechaIni = colaboradorServicioFechaIni;
       this.colaboradorServicioFechaFin = colaboradorServicioFechaFin;
    }
   
    public ColaboradorServicioId getId() {
        return this.id;
    }
    
    public void setId(ColaboradorServicioId id) {
        this.id = id;
    }
    public Colaborador getColaborador() {
        return this.colaborador;
    }
    
    public void setColaborador(Colaborador colaborador) {
        this.colaborador = colaborador;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Date getColaboradorServicioFechaIni() {
        return this.colaboradorServicioFechaIni;
    }
    
    public void setColaboradorServicioFechaIni(Date colaboradorServicioFechaIni) {
        this.colaboradorServicioFechaIni = colaboradorServicioFechaIni;
    }
    public Date getColaboradorServicioFechaFin() {
        return this.colaboradorServicioFechaFin;
    }
    
    public void setColaboradorServicioFechaFin(Date colaboradorServicioFechaFin) {
        this.colaboradorServicioFechaFin = colaboradorServicioFechaFin;
    }




}


