package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Colaborador generated by hbm2java
 */
public class Colaborador  implements java.io.Serializable {


     private Integer colaboradorId;
     private Usuario usuario;
     private String colaboradorNombre;
     private String colaboradorApellido;
     private String colaboradorNumeroIdentificacion;
     private String colaboradorNumeroCelular;
     private String colaboradorNumeroTelefono;
     private String colaboradorDireccion;
     private String colaboradorBarrio;
     private String colaboradorCorreoElctronico;
     private Date colaboradorFechaNacimiento;
     private Date colaboradorFechaCreacion;
     private Date colaboradorFechaModificacion;
     private Set<ColaboradorServicio> colaboradorServicios = new HashSet<ColaboradorServicio>(0);
     private Set<Salida> salidas = new HashSet<Salida>(0);
     private Set<Entrada> entradas = new HashSet<Entrada>(0);

    public Colaborador() {
    }

	
    public Colaborador(Integer colaboradorId, String colaboradorNombre, String colaboradorApellido, String colaboradorNumeroIdentificacion, String colaboradorNumeroCelular, String colaboradorDireccion, String colaboradorBarrio) {
        this.colaboradorId = colaboradorId;
        this.colaboradorNombre = colaboradorNombre;
        this.colaboradorApellido = colaboradorApellido;
        this.colaboradorNumeroIdentificacion = colaboradorNumeroIdentificacion;
        this.colaboradorNumeroCelular = colaboradorNumeroCelular;
        this.colaboradorDireccion = colaboradorDireccion;
        this.colaboradorBarrio = colaboradorBarrio;
    }
    public Colaborador(Integer colaboradorId, Usuario usuario, String colaboradorNombre, String colaboradorApellido, String colaboradorNumeroIdentificacion, String colaboradorNumeroCelular, String colaboradorNumeroTelefono, String colaboradorDireccion, String colaboradorBarrio, String colaboradorCorreoElctronico, Date colaboradorFechaNacimiento, Date colaboradorFechaCreacion, Date colaboradorFechaModificacion, Set<ColaboradorServicio> colaboradorServicios, Set<Salida> salidas, Set<Entrada> entradas) {
       this.colaboradorId = colaboradorId;
       this.usuario = usuario;
       this.colaboradorNombre = colaboradorNombre;
       this.colaboradorApellido = colaboradorApellido;
       this.colaboradorNumeroIdentificacion = colaboradorNumeroIdentificacion;
       this.colaboradorNumeroCelular = colaboradorNumeroCelular;
       this.colaboradorNumeroTelefono = colaboradorNumeroTelefono;
       this.colaboradorDireccion = colaboradorDireccion;
       this.colaboradorBarrio = colaboradorBarrio;
       this.colaboradorCorreoElctronico = colaboradorCorreoElctronico;
       this.colaboradorFechaNacimiento = colaboradorFechaNacimiento;
       this.colaboradorFechaCreacion = colaboradorFechaCreacion;
       this.colaboradorFechaModificacion = colaboradorFechaModificacion;
       this.colaboradorServicios = colaboradorServicios;
       this.salidas = salidas;
       this.entradas = entradas;
    }
   
    public Integer getColaboradorId() {
        return this.colaboradorId;
    }
    
    public void setColaboradorId(Integer colaboradorId) {
        this.colaboradorId = colaboradorId;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getColaboradorNombre() {
        return this.colaboradorNombre;
    }
    
    public void setColaboradorNombre(String colaboradorNombre) {
        this.colaboradorNombre = colaboradorNombre;
    }
    public String getColaboradorApellido() {
        return this.colaboradorApellido;
    }
    
    public void setColaboradorApellido(String colaboradorApellido) {
        this.colaboradorApellido = colaboradorApellido;
    }
    public String getColaboradorNumeroIdentificacion() {
        return this.colaboradorNumeroIdentificacion;
    }
    
    public void setColaboradorNumeroIdentificacion(String colaboradorNumeroIdentificacion) {
        this.colaboradorNumeroIdentificacion = colaboradorNumeroIdentificacion;
    }
    public String getColaboradorNumeroCelular() {
        return this.colaboradorNumeroCelular;
    }
    
    public void setColaboradorNumeroCelular(String colaboradorNumeroCelular) {
        this.colaboradorNumeroCelular = colaboradorNumeroCelular;
    }
    public String getColaboradorNumeroTelefono() {
        return this.colaboradorNumeroTelefono;
    }
    
    public void setColaboradorNumeroTelefono(String colaboradorNumeroTelefono) {
        this.colaboradorNumeroTelefono = colaboradorNumeroTelefono;
    }
    public String getColaboradorDireccion() {
        return this.colaboradorDireccion;
    }
    
    public void setColaboradorDireccion(String colaboradorDireccion) {
        this.colaboradorDireccion = colaboradorDireccion;
    }
    public String getColaboradorBarrio() {
        return this.colaboradorBarrio;
    }
    
    public void setColaboradorBarrio(String colaboradorBarrio) {
        this.colaboradorBarrio = colaboradorBarrio;
    }
    public String getColaboradorCorreoElctronico() {
        return this.colaboradorCorreoElctronico;
    }
    
    public void setColaboradorCorreoElctronico(String colaboradorCorreoElctronico) {
        this.colaboradorCorreoElctronico = colaboradorCorreoElctronico;
    }
    public Date getColaboradorFechaNacimiento() {
        return this.colaboradorFechaNacimiento;
    }
    
    public void setColaboradorFechaNacimiento(Date colaboradorFechaNacimiento) {
        this.colaboradorFechaNacimiento = colaboradorFechaNacimiento;
    }
    public Date getColaboradorFechaCreacion() {
        return this.colaboradorFechaCreacion;
    }
    
    public void setColaboradorFechaCreacion(Date colaboradorFechaCreacion) {
        this.colaboradorFechaCreacion = colaboradorFechaCreacion;
    }
    public Date getColaboradorFechaModificacion() {
        return this.colaboradorFechaModificacion;
    }
    
    public void setColaboradorFechaModificacion(Date colaboradorFechaModificacion) {
        this.colaboradorFechaModificacion = colaboradorFechaModificacion;
    }
    public Set<ColaboradorServicio> getColaboradorServicios() {
        return this.colaboradorServicios;
    }
    
    public void setColaboradorServicios(Set<ColaboradorServicio> colaboradorServicios) {
        this.colaboradorServicios = colaboradorServicios;
    }
    public Set<Salida> getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set<Salida> salidas) {
        this.salidas = salidas;
    }
    public Set<Entrada> getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set<Entrada> entradas) {
        this.entradas = entradas;
    }




}


