package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Consumo generated by hbm2java
 */
public class Consumo  implements java.io.Serializable {


     private Integer consumoId;
     private Double consumoTotalIngreso;
     private Date consumoFecha;
     private Set<Ingreso> ingresos = new HashSet<Ingreso>(0);
     private Set<Membresia> membresias = new HashSet<Membresia>(0);

    public Consumo() {
    }

	
    public Consumo(Integer consumoId) {
        this.consumoId = consumoId;
    }
    public Consumo(Integer consumoId, Double consumoTotalIngreso, Date consumoFecha, Set<Ingreso> ingresos, Set<Membresia> membresias) {
       this.consumoId = consumoId;
       this.consumoTotalIngreso = consumoTotalIngreso;
       this.consumoFecha = consumoFecha;
       this.ingresos = ingresos;
       this.membresias = membresias;
    }
   
    public Integer getConsumoId() {
        return this.consumoId;
    }
    
    public void setConsumoId(Integer consumoId) {
        this.consumoId = consumoId;
    }
    public Double getConsumoTotalIngreso() {
        return this.consumoTotalIngreso;
    }
    
    public void setConsumoTotalIngreso(Double consumoTotalIngreso) {
        this.consumoTotalIngreso = consumoTotalIngreso;
    }
    public Date getConsumoFecha() {
        return this.consumoFecha;
    }
    
    public void setConsumoFecha(Date consumoFecha) {
        this.consumoFecha = consumoFecha;
    }
    public Set<Ingreso> getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set<Ingreso> ingresos) {
        this.ingresos = ingresos;
    }
    public Set<Membresia> getMembresias() {
        return this.membresias;
    }
    
    public void setMembresias(Set<Membresia> membresias) {
        this.membresias = membresias;
    }




}


