package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * Egreso generated by hbm2java
 */
public class Egreso  implements java.io.Serializable {


     private Integer egresoId;
     private ClaseTipo claseTipo;
     private Double egresoValor;
     private Date egresoFecha;

    public Egreso() {
    }

	
    public Egreso(Integer egresoId) {
        this.egresoId = egresoId;
    }
    public Egreso(Integer egresoId, ClaseTipo claseTipo, Double egresoValor, Date egresoFecha) {
       this.egresoId = egresoId;
       this.claseTipo = claseTipo;
       this.egresoValor = egresoValor;
       this.egresoFecha = egresoFecha;
    }
   
    public Integer getEgresoId() {
        return this.egresoId;
    }
    
    public void setEgresoId(Integer egresoId) {
        this.egresoId = egresoId;
    }
    public ClaseTipo getClaseTipo() {
        return this.claseTipo;
    }
    
    public void setClaseTipo(ClaseTipo claseTipo) {
        this.claseTipo = claseTipo;
    }
    public Double getEgresoValor() {
        return this.egresoValor;
    }
    
    public void setEgresoValor(Double egresoValor) {
        this.egresoValor = egresoValor;
    }
    public Date getEgresoFecha() {
        return this.egresoFecha;
    }
    
    public void setEgresoFecha(Date egresoFecha) {
        this.egresoFecha = egresoFecha;
    }




}


