package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * Membresia generated by hbm2java
 */
public class Membresia  implements java.io.Serializable {


     private Integer membresiaId;
     private Consumo consumo;
     private Miembro miembro;
     private Double membresiaPorcentajeDescuento;
     private Integer membresiaNivel;
     private Integer membresiaPuntos;
     private Integer membresiaIzquierda;
     private Integer membresiaDerecha;
     private Date membresiaFecha;

    public Membresia() {
    }

	
    public Membresia(Integer membresiaId) {
        this.membresiaId = membresiaId;
    }
    public Membresia(Integer membresiaId, Consumo consumo, Miembro miembro, Double membresiaPorcentajeDescuento, Integer membresiaNivel, Integer membresiaPuntos, Integer membresiaIzquierda, Integer membresiaDerecha, Date membresiaFecha) {
       this.membresiaId = membresiaId;
       this.consumo = consumo;
       this.miembro = miembro;
       this.membresiaPorcentajeDescuento = membresiaPorcentajeDescuento;
       this.membresiaNivel = membresiaNivel;
       this.membresiaPuntos = membresiaPuntos;
       this.membresiaIzquierda = membresiaIzquierda;
       this.membresiaDerecha = membresiaDerecha;
       this.membresiaFecha = membresiaFecha;
    }
   
    public Integer getMembresiaId() {
        return this.membresiaId;
    }
    
    public void setMembresiaId(Integer membresiaId) {
        this.membresiaId = membresiaId;
    }
    public Consumo getConsumo() {
        return this.consumo;
    }
    
    public void setConsumo(Consumo consumo) {
        this.consumo = consumo;
    }
    public Miembro getMiembro() {
        return this.miembro;
    }
    
    public void setMiembro(Miembro miembro) {
        this.miembro = miembro;
    }
    public Double getMembresiaPorcentajeDescuento() {
        return this.membresiaPorcentajeDescuento;
    }
    
    public void setMembresiaPorcentajeDescuento(Double membresiaPorcentajeDescuento) {
        this.membresiaPorcentajeDescuento = membresiaPorcentajeDescuento;
    }
    public Integer getMembresiaNivel() {
        return this.membresiaNivel;
    }
    
    public void setMembresiaNivel(Integer membresiaNivel) {
        this.membresiaNivel = membresiaNivel;
    }
    public Integer getMembresiaPuntos() {
        return this.membresiaPuntos;
    }
    
    public void setMembresiaPuntos(Integer membresiaPuntos) {
        this.membresiaPuntos = membresiaPuntos;
    }
    public Integer getMembresiaIzquierda() {
        return this.membresiaIzquierda;
    }
    
    public void setMembresiaIzquierda(Integer membresiaIzquierda) {
        this.membresiaIzquierda = membresiaIzquierda;
    }
    public Integer getMembresiaDerecha() {
        return this.membresiaDerecha;
    }
    
    public void setMembresiaDerecha(Integer membresiaDerecha) {
        this.membresiaDerecha = membresiaDerecha;
    }
    public Date getMembresiaFecha() {
        return this.membresiaFecha;
    }
    
    public void setMembresiaFecha(Date membresiaFecha) {
        this.membresiaFecha = membresiaFecha;
    }




}


