package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Miembro generated by hbm2java
 */
public class Miembro  implements java.io.Serializable {


     private Integer miembroId;
     private Usuario usuario;
     private String miembroNombre;
     private String miembroApellido;
     private String miembroNumeroIdentificacion;
     private String miembroNumeroCelular;
     private String miembroNumeroTelefono;
     private String miembroDireccion;
     private String miembroBarrio;
     private String miembroCorreoElctronico;
     private Date miembroFechaNacimiento;
     private Date miembroFechaCreacion;
     private Date miembroFechaModificacion;
     private Set<Membresia> membresias = new HashSet<Membresia>(0);
     private Set<Salida> salidas = new HashSet<Salida>(0);
     private Set<Ingreso> ingresos = new HashSet<Ingreso>(0);
     private Set<Entrada> entradas = new HashSet<Entrada>(0);

    public Miembro() {
    }

	
    public Miembro(Integer miembroId, String miembroNombre, String miembroApellido, String miembroNumeroIdentificacion, String miembroNumeroCelular, String miembroDireccion, String miembroBarrio) {
        this.miembroId = miembroId;
        this.miembroNombre = miembroNombre;
        this.miembroApellido = miembroApellido;
        this.miembroNumeroIdentificacion = miembroNumeroIdentificacion;
        this.miembroNumeroCelular = miembroNumeroCelular;
        this.miembroDireccion = miembroDireccion;
        this.miembroBarrio = miembroBarrio;
    }
    public Miembro(Integer miembroId, Usuario usuario, String miembroNombre, String miembroApellido, String miembroNumeroIdentificacion, String miembroNumeroCelular, String miembroNumeroTelefono, String miembroDireccion, String miembroBarrio, String miembroCorreoElctronico, Date miembroFechaNacimiento, Date miembroFechaCreacion, Date miembroFechaModificacion, Set<Membresia> membresias, Set<Salida> salidas, Set<Ingreso> ingresos, Set<Entrada> entradas) {
       this.miembroId = miembroId;
       this.usuario = usuario;
       this.miembroNombre = miembroNombre;
       this.miembroApellido = miembroApellido;
       this.miembroNumeroIdentificacion = miembroNumeroIdentificacion;
       this.miembroNumeroCelular = miembroNumeroCelular;
       this.miembroNumeroTelefono = miembroNumeroTelefono;
       this.miembroDireccion = miembroDireccion;
       this.miembroBarrio = miembroBarrio;
       this.miembroCorreoElctronico = miembroCorreoElctronico;
       this.miembroFechaNacimiento = miembroFechaNacimiento;
       this.miembroFechaCreacion = miembroFechaCreacion;
       this.miembroFechaModificacion = miembroFechaModificacion;
       this.membresias = membresias;
       this.salidas = salidas;
       this.ingresos = ingresos;
       this.entradas = entradas;
    }
   
    public Integer getMiembroId() {
        return this.miembroId;
    }
    
    public void setMiembroId(Integer miembroId) {
        this.miembroId = miembroId;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getMiembroNombre() {
        return this.miembroNombre;
    }
    
    public void setMiembroNombre(String miembroNombre) {
        this.miembroNombre = miembroNombre;
    }
    public String getMiembroApellido() {
        return this.miembroApellido;
    }
    
    public void setMiembroApellido(String miembroApellido) {
        this.miembroApellido = miembroApellido;
    }
    public String getMiembroNumeroIdentificacion() {
        return this.miembroNumeroIdentificacion;
    }
    
    public void setMiembroNumeroIdentificacion(String miembroNumeroIdentificacion) {
        this.miembroNumeroIdentificacion = miembroNumeroIdentificacion;
    }
    public String getMiembroNumeroCelular() {
        return this.miembroNumeroCelular;
    }
    
    public void setMiembroNumeroCelular(String miembroNumeroCelular) {
        this.miembroNumeroCelular = miembroNumeroCelular;
    }
    public String getMiembroNumeroTelefono() {
        return this.miembroNumeroTelefono;
    }
    
    public void setMiembroNumeroTelefono(String miembroNumeroTelefono) {
        this.miembroNumeroTelefono = miembroNumeroTelefono;
    }
    public String getMiembroDireccion() {
        return this.miembroDireccion;
    }
    
    public void setMiembroDireccion(String miembroDireccion) {
        this.miembroDireccion = miembroDireccion;
    }
    public String getMiembroBarrio() {
        return this.miembroBarrio;
    }
    
    public void setMiembroBarrio(String miembroBarrio) {
        this.miembroBarrio = miembroBarrio;
    }
    public String getMiembroCorreoElctronico() {
        return this.miembroCorreoElctronico;
    }
    
    public void setMiembroCorreoElctronico(String miembroCorreoElctronico) {
        this.miembroCorreoElctronico = miembroCorreoElctronico;
    }
    public Date getMiembroFechaNacimiento() {
        return this.miembroFechaNacimiento;
    }
    
    public void setMiembroFechaNacimiento(Date miembroFechaNacimiento) {
        this.miembroFechaNacimiento = miembroFechaNacimiento;
    }
    public Date getMiembroFechaCreacion() {
        return this.miembroFechaCreacion;
    }
    
    public void setMiembroFechaCreacion(Date miembroFechaCreacion) {
        this.miembroFechaCreacion = miembroFechaCreacion;
    }
    public Date getMiembroFechaModificacion() {
        return this.miembroFechaModificacion;
    }
    
    public void setMiembroFechaModificacion(Date miembroFechaModificacion) {
        this.miembroFechaModificacion = miembroFechaModificacion;
    }
    public Set<Membresia> getMembresias() {
        return this.membresias;
    }
    
    public void setMembresias(Set<Membresia> membresias) {
        this.membresias = membresias;
    }
    public Set<Salida> getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set<Salida> salidas) {
        this.salidas = salidas;
    }
    public Set<Ingreso> getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set<Ingreso> ingresos) {
        this.ingresos = ingresos;
    }
    public Set<Entrada> getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set<Entrada> entradas) {
        this.entradas = entradas;
    }




}


