package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final



/**
 * PgStatStatements generated by hbm2java
 */
public class PgStatStatements  implements java.io.Serializable {


     private PgStatStatementsId id;

    public PgStatStatements() {
    }

    public PgStatStatements(PgStatStatementsId id) {
       this.id = id;
    }
   
    public PgStatStatementsId getId() {
        return this.id;
    }
    
    public void setId(PgStatStatementsId id) {
        this.id = id;
    }




}


