package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer productoId;
     private ClaseTipo claseTipo;
     private String productoBeneficios;
     private Integer productoCantidad;
     private String productoImagen;
     private Date productoFechaCrecaion;
     private Date productoFechaModificacion;
     private Set<Entrada> entradas = new HashSet<Entrada>(0);
     private Set<Salida> salidas = new HashSet<Salida>(0);
     private Set<Servicio> servicios = new HashSet<Servicio>(0);
     private Set<Ingreso> ingresos = new HashSet<Ingreso>(0);

    public Producto() {
    }

	
    public Producto(Integer productoId) {
        this.productoId = productoId;
    }
    public Producto(Integer productoId, ClaseTipo claseTipo, String productoBeneficios, Integer productoCantidad, String productoImagen, Date productoFechaCrecaion, Date productoFechaModificacion, Set<Entrada> entradas, Set<Salida> salidas, Set<Servicio> servicios, Set<Ingreso> ingresos) {
       this.productoId = productoId;
       this.claseTipo = claseTipo;
       this.productoBeneficios = productoBeneficios;
       this.productoCantidad = productoCantidad;
       this.productoImagen = productoImagen;
       this.productoFechaCrecaion = productoFechaCrecaion;
       this.productoFechaModificacion = productoFechaModificacion;
       this.entradas = entradas;
       this.salidas = salidas;
       this.servicios = servicios;
       this.ingresos = ingresos;
    }
   
    public Integer getProductoId() {
        return this.productoId;
    }
    
    public void setProductoId(Integer productoId) {
        this.productoId = productoId;
    }
    public ClaseTipo getClaseTipo() {
        return this.claseTipo;
    }
    
    public void setClaseTipo(ClaseTipo claseTipo) {
        this.claseTipo = claseTipo;
    }
    public String getProductoBeneficios() {
        return this.productoBeneficios;
    }
    
    public void setProductoBeneficios(String productoBeneficios) {
        this.productoBeneficios = productoBeneficios;
    }
    public Integer getProductoCantidad() {
        return this.productoCantidad;
    }
    
    public void setProductoCantidad(Integer productoCantidad) {
        this.productoCantidad = productoCantidad;
    }
    public String getProductoImagen() {
        return this.productoImagen;
    }
    
    public void setProductoImagen(String productoImagen) {
        this.productoImagen = productoImagen;
    }
    public Date getProductoFechaCrecaion() {
        return this.productoFechaCrecaion;
    }
    
    public void setProductoFechaCrecaion(Date productoFechaCrecaion) {
        this.productoFechaCrecaion = productoFechaCrecaion;
    }
    public Date getProductoFechaModificacion() {
        return this.productoFechaModificacion;
    }
    
    public void setProductoFechaModificacion(Date productoFechaModificacion) {
        this.productoFechaModificacion = productoFechaModificacion;
    }
    public Set<Entrada> getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set<Entrada> entradas) {
        this.entradas = entradas;
    }
    public Set<Salida> getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set<Salida> salidas) {
        this.salidas = salidas;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }
    public Set<Ingreso> getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set<Ingreso> ingresos) {
        this.ingresos = ingresos;
    }




}


