package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final



/**
 * Puntos generated by hbm2java
 */
public class Puntos  implements java.io.Serializable {


     private Integer puntosId;
     private ClaseTipo claseTipo;
     private Integer puntosPuntos;

    public Puntos() {
    }

	
    public Puntos(Integer puntosId) {
        this.puntosId = puntosId;
    }
    public Puntos(Integer puntosId, ClaseTipo claseTipo, Integer puntosPuntos) {
       this.puntosId = puntosId;
       this.claseTipo = claseTipo;
       this.puntosPuntos = puntosPuntos;
    }
   
    public Integer getPuntosId() {
        return this.puntosId;
    }
    
    public void setPuntosId(Integer puntosId) {
        this.puntosId = puntosId;
    }
    public ClaseTipo getClaseTipo() {
        return this.claseTipo;
    }
    
    public void setClaseTipo(ClaseTipo claseTipo) {
        this.claseTipo = claseTipo;
    }
    public Integer getPuntosPuntos() {
        return this.puntosPuntos;
    }
    
    public void setPuntosPuntos(Integer puntosPuntos) {
        this.puntosPuntos = puntosPuntos;
    }




}


