package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private Integer servicioId;
     private ClaseTipo claseTipo;
     private String servicioBeneficios;
     private String servicioImagen;
     private Date servicioFechaCreacion;
     private Date servicionFechaModificacion;
     private Set<ColaboradorServicio> colaboradorServicios = new HashSet<ColaboradorServicio>(0);
     private Set<Salida> salidas = new HashSet<Salida>(0);
     private Set<Entrada> entradas = new HashSet<Entrada>(0);
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<Ingreso> ingresos = new HashSet<Ingreso>(0);

    public Servicio() {
    }

	
    public Servicio(Integer servicioId) {
        this.servicioId = servicioId;
    }
    public Servicio(Integer servicioId, ClaseTipo claseTipo, String servicioBeneficios, String servicioImagen, Date servicioFechaCreacion, Date servicionFechaModificacion, Set<ColaboradorServicio> colaboradorServicios, Set<Salida> salidas, Set<Entrada> entradas, Set<Producto> productos, Set<Ingreso> ingresos) {
       this.servicioId = servicioId;
       this.claseTipo = claseTipo;
       this.servicioBeneficios = servicioBeneficios;
       this.servicioImagen = servicioImagen;
       this.servicioFechaCreacion = servicioFechaCreacion;
       this.servicionFechaModificacion = servicionFechaModificacion;
       this.colaboradorServicios = colaboradorServicios;
       this.salidas = salidas;
       this.entradas = entradas;
       this.productos = productos;
       this.ingresos = ingresos;
    }
   
    public Integer getServicioId() {
        return this.servicioId;
    }
    
    public void setServicioId(Integer servicioId) {
        this.servicioId = servicioId;
    }
    public ClaseTipo getClaseTipo() {
        return this.claseTipo;
    }
    
    public void setClaseTipo(ClaseTipo claseTipo) {
        this.claseTipo = claseTipo;
    }
    public String getServicioBeneficios() {
        return this.servicioBeneficios;
    }
    
    public void setServicioBeneficios(String servicioBeneficios) {
        this.servicioBeneficios = servicioBeneficios;
    }
    public String getServicioImagen() {
        return this.servicioImagen;
    }
    
    public void setServicioImagen(String servicioImagen) {
        this.servicioImagen = servicioImagen;
    }
    public Date getServicioFechaCreacion() {
        return this.servicioFechaCreacion;
    }
    
    public void setServicioFechaCreacion(Date servicioFechaCreacion) {
        this.servicioFechaCreacion = servicioFechaCreacion;
    }
    public Date getServicionFechaModificacion() {
        return this.servicionFechaModificacion;
    }
    
    public void setServicionFechaModificacion(Date servicionFechaModificacion) {
        this.servicionFechaModificacion = servicionFechaModificacion;
    }
    public Set<ColaboradorServicio> getColaboradorServicios() {
        return this.colaboradorServicios;
    }
    
    public void setColaboradorServicios(Set<ColaboradorServicio> colaboradorServicios) {
        this.colaboradorServicios = colaboradorServicios;
    }
    public Set<Salida> getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set<Salida> salidas) {
        this.salidas = salidas;
    }
    public Set<Entrada> getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set<Entrada> entradas) {
        this.entradas = entradas;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
    public Set<Ingreso> getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set<Ingreso> ingresos) {
        this.ingresos = ingresos;
    }




}


