package com.nuck.modelo;
// Generated 23-jun-2017 1:38:17 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer usuarioId;
     private String usuarioNombre;
     private String usuarioPasswd;
     private String usuarioAdmin;
     private String usuarioImagen;
     private Date usuarioFechaCreacion;
     private Date usuarioFechaModificacion;
     private Set<Miembro> miembros = new HashSet<Miembro>(0);
     private Set<Colaborador> colaboradors = new HashSet<Colaborador>(0);

    public Usuario() {
    }

	
    public Usuario(Integer usuarioId, String usuarioNombre, String usuarioPasswd) {
        this.usuarioId = usuarioId;
        this.usuarioNombre = usuarioNombre;
        this.usuarioPasswd = usuarioPasswd;
    }
    public Usuario(Integer usuarioId, String usuarioNombre, String usuarioPasswd, String usuarioAdmin, String usuarioImagen, Date usuarioFechaCreacion, Date usuarioFechaModificacion, Set<Miembro> miembros, Set<Colaborador> colaboradors) {
       this.usuarioId = usuarioId;
       this.usuarioNombre = usuarioNombre;
       this.usuarioPasswd = usuarioPasswd;
       this.usuarioAdmin = usuarioAdmin;
       this.usuarioImagen = usuarioImagen;
       this.usuarioFechaCreacion = usuarioFechaCreacion;
       this.usuarioFechaModificacion = usuarioFechaModificacion;
       this.miembros = miembros;
       this.colaboradors = colaboradors;
    }
   
    public Integer getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }
    public String getUsuarioNombre() {
        return this.usuarioNombre;
    }
    
    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }
    public String getUsuarioPasswd() {
        return this.usuarioPasswd;
    }
    
    public void setUsuarioPasswd(String usuarioPasswd) {
        this.usuarioPasswd = usuarioPasswd;
    }
    public String getUsuarioAdmin() {
        return this.usuarioAdmin;
    }
    
    public void setUsuarioAdmin(String usuarioAdmin) {
        this.usuarioAdmin = usuarioAdmin;
    }
    public String getUsuarioImagen() {
        return this.usuarioImagen;
    }
    
    public void setUsuarioImagen(String usuarioImagen) {
        this.usuarioImagen = usuarioImagen;
    }
    public Date getUsuarioFechaCreacion() {
        return this.usuarioFechaCreacion;
    }
    
    public void setUsuarioFechaCreacion(Date usuarioFechaCreacion) {
        this.usuarioFechaCreacion = usuarioFechaCreacion;
    }
    public Date getUsuarioFechaModificacion() {
        return this.usuarioFechaModificacion;
    }
    
    public void setUsuarioFechaModificacion(Date usuarioFechaModificacion) {
        this.usuarioFechaModificacion = usuarioFechaModificacion;
    }
    public Set<Miembro> getMiembros() {
        return this.miembros;
    }
    
    public void setMiembros(Set<Miembro> miembros) {
        this.miembros = miembros;
    }
    public Set<Colaborador> getColaboradors() {
        return this.colaboradors;
    }
    
    public void setColaboradors(Set<Colaborador> colaboradors) {
        this.colaboradors = colaboradors;
    }




}


